version: "3.5"

networks:
  internal:

services:
  mvc:
    build: ./src/VaultClient/.
    ports:
     - "80:80"
     - "443:443"
    networks:
      - internal
    restart: always
  vault:
    image: vault:1.1.1
    container_name: vault
    ports:
      - 8200:8200
    networks:
      - internal
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_DEV_ROOT_TOKEN_ID=secret
    cap_add:
      - IPC_LOCK